import { ModelInfo } from './types';

export const MODEL_SEED: ModelInfo[] = [
  {
    id: 'anthropic/claude-3.5-haiku',
    label: 'Anthropic: Claude 3.5 Haiku',
    inputCostPerToken: 8e-7,
    outputCostPerToken: 0.000004,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'anthropic/claude-3.5-sonnet',
    label: 'Anthropic: Claude 3.5 Sonnet',
    inputCostPerToken: 0.000006,
    outputCostPerToken: 0.00003,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'anthropic/claude-3.7-sonnet',
    label: 'Anthropic: Claude 3.7 Sonnet',
    inputCostPerToken: 0.000003,
    outputCostPerToken: 0.000015,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'anthropic/claude-3.7-sonnet:thinking',
    label: 'Anthropic: Claude 3.7 Sonnet (thinking)',
    inputCostPerToken: 0.000003,
    outputCostPerToken: 0.000015,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'anthropic/claude-haiku-4.5',
    label: 'Anthropic: Claude Haiku 4.5',
    inputCostPerToken: 0.000001,
    outputCostPerToken: 0.000005,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'anthropic/claude-opus-4',
    label: 'Anthropic: Claude Opus 4',
    inputCostPerToken: 0.000015,
    outputCostPerToken: 0.000075,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'anthropic/claude-opus-4.1',
    label: 'Anthropic: Claude Opus 4.1',
    inputCostPerToken: 0.000015,
    outputCostPerToken: 0.000075,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'anthropic/claude-opus-4.5',
    label: 'Anthropic: Claude Opus 4.5',
    inputCostPerToken: 0.000005,
    outputCostPerToken: 0.000025,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'anthropic/claude-sonnet-4',
    label: 'Anthropic: Claude Sonnet 4',
    inputCostPerToken: 0.000003,
    outputCostPerToken: 0.000015,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'anthropic/claude-sonnet-4.5',
    label: 'Anthropic: Claude Sonnet 4.5',
    inputCostPerToken: 0.000003,
    outputCostPerToken: 0.000015,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'google/gemini-2.0-flash-001',
    label: 'Google: Gemini 2.0 Flash',
    inputCostPerToken: 1e-7,
    outputCostPerToken: 4e-7,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemini-2.0-flash-lite-001',
    label: 'Google: Gemini 2.0 Flash Lite',
    inputCostPerToken: 7.5e-8,
    outputCostPerToken: 3e-7,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemini-2.5-flash',
    label: 'Google: Gemini 2.5 Flash',
    inputCostPerToken: 3e-7,
    outputCostPerToken: 0.0000025,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'google/gemini-2.5-flash-image',
    label: 'Google: Gemini 2.5 Flash Image (Nano Banana)',
    inputCostPerToken: 3e-7,
    outputCostPerToken: 0.0000025,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemini-2.5-flash-lite',
    label: 'Google: Gemini 2.5 Flash Lite',
    inputCostPerToken: 1e-7,
    outputCostPerToken: 4e-7,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'google/gemini-2.5-flash-lite-preview-09-2025',
    label: 'Google: Gemini 2.5 Flash Lite Preview 09-2025',
    inputCostPerToken: 1e-7,
    outputCostPerToken: 4e-7,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'google/gemini-2.5-flash-preview-09-2025',
    label: 'Google: Gemini 2.5 Flash Preview 09-2025',
    inputCostPerToken: 3e-7,
    outputCostPerToken: 0.0000025,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'google/gemini-2.5-pro',
    label: 'Google: Gemini 2.5 Pro',
    inputCostPerToken: 0.00000125,
    outputCostPerToken: 0.00001,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'google/gemini-2.5-pro-preview-05-06',
    label: 'Google: Gemini 2.5 Pro Preview 05-06',
    inputCostPerToken: 0.00000125,
    outputCostPerToken: 0.00001,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'google/gemini-2.5-pro-preview',
    label: 'Google: Gemini 2.5 Pro Preview 06-05',
    inputCostPerToken: 0.00000125,
    outputCostPerToken: 0.00001,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'google/gemini-3-flash-preview',
    label: 'Google: Gemini 3 Flash Preview',
    inputCostPerToken: 5e-7,
    outputCostPerToken: 0.000003,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'google/gemini-3-pro-preview',
    label: 'Google: Gemini 3 Pro Preview',
    inputCostPerToken: 0.000002,
    outputCostPerToken: 0.000012,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'google/gemma-2-27b-it',
    label: 'Google: Gemma 2 27B',
    inputCostPerToken: 6.5e-7,
    outputCostPerToken: 6.5e-7,
    supportsVision: false,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemma-2-9b-it',
    label: 'Google: Gemma 2 9B',
    inputCostPerToken: 3e-8,
    outputCostPerToken: 9e-8,
    supportsVision: false,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemma-3-12b-it',
    label: 'Google: Gemma 3 12B',
    inputCostPerToken: 3e-8,
    outputCostPerToken: 1e-7,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemma-3-12b-it:free',
    label: 'Google: Gemma 3 12B (free)',
    inputCostPerToken: 0,
    outputCostPerToken: 0,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemma-3-27b-it',
    label: 'Google: Gemma 3 27B',
    inputCostPerToken: 4e-8,
    outputCostPerToken: 1.5e-7,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemma-3-27b-it:free',
    label: 'Google: Gemma 3 27B (free)',
    inputCostPerToken: 0,
    outputCostPerToken: 0,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemma-3-4b-it',
    label: 'Google: Gemma 3 4B',
    inputCostPerToken: 1.703012e-8,
    outputCostPerToken: 6.81536e-8,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemma-3-4b-it:free',
    label: 'Google: Gemma 3 4B (free)',
    inputCostPerToken: 0,
    outputCostPerToken: 0,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemma-3n-e2b-it:free',
    label: 'Google: Gemma 3n 2B (free)',
    inputCostPerToken: 0,
    outputCostPerToken: 0,
    supportsVision: false,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemma-3n-e4b-it',
    label: 'Google: Gemma 3n 4B',
    inputCostPerToken: 2e-8,
    outputCostPerToken: 4e-8,
    supportsVision: false,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemma-3n-e4b-it:free',
    label: 'Google: Gemma 3n 4B (free)',
    inputCostPerToken: 0,
    outputCostPerToken: 0,
    supportsVision: false,
    supportsThinkingLevels: false,
  },
  {
    id: 'google/gemini-3-pro-image-preview',
    label: 'Google: Nano Banana Pro (Gemini 3 Pro Image Preview)',
    inputCostPerToken: 0.000002,
    outputCostPerToken: 0.000012,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'moonshotai/kimi-k2',
    label: 'MoonshotAI: Kimi K2 0711',
    inputCostPerToken: 5e-7,
    outputCostPerToken: 0.0000024,
    supportsVision: false,
    supportsThinkingLevels: false,
  },
  {
    id: 'moonshotai/kimi-k2-thinking',
    label: 'MoonshotAI: Kimi K2 Thinking',
    inputCostPerToken: 4e-7,
    outputCostPerToken: 0.00000175,
    supportsVision: false,
    supportsThinkingLevels: true,
  },
  {
    id: 'moonshotai/kimi-k2.5',
    label: 'MoonshotAI: Kimi K2.5',
    inputCostPerToken: 5e-7,
    outputCostPerToken: 0.0000028,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-audio',
    label: 'OpenAI: GPT Audio',
    inputCostPerToken: 0.0000025,
    outputCostPerToken: 0.00001,
    supportsVision: false,
    supportsThinkingLevels: false,
  },
  {
    id: 'openai/gpt-audio-mini',
    label: 'OpenAI: GPT Audio Mini',
    inputCostPerToken: 6e-7,
    outputCostPerToken: 0.0000024,
    supportsVision: false,
    supportsThinkingLevels: false,
  },
  {
    id: 'openai/gpt-4o-audio-preview',
    label: 'OpenAI: GPT-4o Audio',
    inputCostPerToken: 0.0000025,
    outputCostPerToken: 0.00001,
    supportsVision: false,
    supportsThinkingLevels: false,
  },
  {
    id: 'openai/gpt-5',
    label: 'OpenAI: GPT-5',
    inputCostPerToken: 0.00000125,
    outputCostPerToken: 0.00001,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5-chat',
    label: 'OpenAI: GPT-5 Chat',
    inputCostPerToken: 0.00000125,
    outputCostPerToken: 0.00001,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'openai/gpt-5-codex',
    label: 'OpenAI: GPT-5 Codex',
    inputCostPerToken: 0.00000125,
    outputCostPerToken: 0.00001,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5-image',
    label: 'OpenAI: GPT-5 Image',
    inputCostPerToken: 0.00001,
    outputCostPerToken: 0.00001,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5-image-mini',
    label: 'OpenAI: GPT-5 Image Mini',
    inputCostPerToken: 0.0000025,
    outputCostPerToken: 0.000002,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5-mini',
    label: 'OpenAI: GPT-5 Mini',
    inputCostPerToken: 2.5e-7,
    outputCostPerToken: 0.000002,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5-nano',
    label: 'OpenAI: GPT-5 Nano',
    inputCostPerToken: 5e-8,
    outputCostPerToken: 4e-7,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5-pro',
    label: 'OpenAI: GPT-5 Pro',
    inputCostPerToken: 0.000015,
    outputCostPerToken: 0.00012,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5.1',
    label: 'OpenAI: GPT-5.1',
    inputCostPerToken: 0.00000125,
    outputCostPerToken: 0.00001,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5.1-chat',
    label: 'OpenAI: GPT-5.1 Chat',
    inputCostPerToken: 0.00000125,
    outputCostPerToken: 0.00001,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'openai/gpt-5.1-codex',
    label: 'OpenAI: GPT-5.1-Codex',
    inputCostPerToken: 0.00000125,
    outputCostPerToken: 0.00001,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5.1-codex-max',
    label: 'OpenAI: GPT-5.1-Codex-Max',
    inputCostPerToken: 0.00000125,
    outputCostPerToken: 0.00001,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5.1-codex-mini',
    label: 'OpenAI: GPT-5.1-Codex-Mini',
    inputCostPerToken: 2.5e-7,
    outputCostPerToken: 0.000002,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5.2',
    label: 'OpenAI: GPT-5.2',
    inputCostPerToken: 0.00000175,
    outputCostPerToken: 0.000014,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5.2-chat',
    label: 'OpenAI: GPT-5.2 Chat',
    inputCostPerToken: 0.00000175,
    outputCostPerToken: 0.000014,
    supportsVision: true,
    supportsThinkingLevels: false,
  },
  {
    id: 'openai/gpt-5.2-pro',
    label: 'OpenAI: GPT-5.2 Pro',
    inputCostPerToken: 0.000021,
    outputCostPerToken: 0.000168,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-5.2-codex',
    label: 'OpenAI: GPT-5.2-Codex',
    inputCostPerToken: 0.00000175,
    outputCostPerToken: 0.000014,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-oss-120b',
    label: 'OpenAI: gpt-oss-120b',
    inputCostPerToken: 3.9e-8,
    outputCostPerToken: 1.9e-7,
    supportsVision: false,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-oss-120b:exacto',
    label: 'OpenAI: gpt-oss-120b (exacto)',
    inputCostPerToken: 3.9e-8,
    outputCostPerToken: 1.9e-7,
    supportsVision: false,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-oss-120b:free',
    label: 'OpenAI: gpt-oss-120b (free)',
    inputCostPerToken: 0,
    outputCostPerToken: 0,
    supportsVision: false,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-oss-20b',
    label: 'OpenAI: gpt-oss-20b',
    inputCostPerToken: 2e-8,
    outputCostPerToken: 1e-7,
    supportsVision: false,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-oss-20b:free',
    label: 'OpenAI: gpt-oss-20b (free)',
    inputCostPerToken: 0,
    outputCostPerToken: 0,
    supportsVision: false,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/gpt-oss-safeguard-20b',
    label: 'OpenAI: gpt-oss-safeguard-20b',
    inputCostPerToken: 7.5e-8,
    outputCostPerToken: 3e-7,
    supportsVision: false,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/o3',
    label: 'OpenAI: o3',
    inputCostPerToken: 0.000002,
    outputCostPerToken: 0.000008,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/o3-deep-research',
    label: 'OpenAI: o3 Deep Research',
    inputCostPerToken: 0.00001,
    outputCostPerToken: 0.00004,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/o3-mini',
    label: 'OpenAI: o3 Mini',
    inputCostPerToken: 0.0000011,
    outputCostPerToken: 0.0000044,
    supportsVision: false,
    supportsThinkingLevels: false,
  },
  {
    id: 'openai/o3-mini-high',
    label: 'OpenAI: o3 Mini High',
    inputCostPerToken: 0.0000011,
    outputCostPerToken: 0.0000044,
    supportsVision: false,
    supportsThinkingLevels: false,
  },
  {
    id: 'openai/o3-pro',
    label: 'OpenAI: o3 Pro',
    inputCostPerToken: 0.00002,
    outputCostPerToken: 0.00008,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/o4-mini',
    label: 'OpenAI: o4 Mini',
    inputCostPerToken: 0.0000011,
    outputCostPerToken: 0.0000044,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/o4-mini-deep-research',
    label: 'OpenAI: o4 Mini Deep Research',
    inputCostPerToken: 0.000002,
    outputCostPerToken: 0.000008,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'openai/o4-mini-high',
    label: 'OpenAI: o4 Mini High',
    inputCostPerToken: 0.0000011,
    outputCostPerToken: 0.0000044,
    supportsVision: true,
    supportsThinkingLevels: true,
  },
  {
    id: 'z-ai/glm-4.7',
    label: 'Z.AI: GLM 4.7',
    inputCostPerToken: 4e-7,
    outputCostPerToken: 0.0000015,
    supportsVision: false,
    supportsThinkingLevels: true,
  },
  {
    id: 'z-ai/glm-4.7-flash',
    label: 'Z.AI: GLM 4.7 Flash',
    inputCostPerToken: 7e-8,
    outputCostPerToken: 4e-7,
    supportsVision: false,
    supportsThinkingLevels: true,
  },
];
